name: Refresh Meteo Token

on:
  schedule:
    - cron: "0 21 * * *"
    - cron: "0 22 * * *"
    - cron: "0 23 * * *"
    - cron: "0 0 * * *"
    - cron: "0 1 * * *"
    - cron: "0 2 * * *"
    - cron: "0 3 * * *"
    - cron: "0 4 * * *"
    - cron: "0 5 * * *"
    - cron: "0 6 * * *"
    - cron: "0 7 * * *"
    - cron: "0 8 * * *"
    - cron: "0 9 * * *" 
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run bot
        run: node bot/refresh.js
