name: Refresh meteo.nc token

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./bot
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run bot
        working-directory: ./bot
        run: node refresh.js
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
